"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ProjectProperties_1 = require("./ProjectProperties");
exports.GetWelcomePageFieldValues = ProjectProperties_1.GetProjectPropertiesPageFieldValues;
exports.UpdateProjectPhase = ProjectProperties_1.UpdateProjectPhase;
exports.GetCurrentProjectPhase = ProjectProperties_1.GetCurrentProjectPhase;
exports.GetRequestedProjectPhase = ProjectProperties_1.GetRequestedProjectPhase;
const ChangeProjectPhase_1 = require("./ChangeProjectPhase");
exports.ChangeProjectPhase = ChangeProjectPhase_1.default;
const MetadataDefaults_1 = require("./MetadataDefaults");
exports.EnsureLocationBasedMetadataDefaultsReceiverForLibrary = MetadataDefaults_1.EnsureLocationBasedMetadataDefaultsReceiverForLibrary;
exports.SetMetadataDefaultsForLibrary = MetadataDefaults_1.SetMetadataDefaultsForLibrary;
const UpdateFrontpageListViews_1 = require("./UpdateFrontpageListViews");
exports.UpdateFrontpageListViews = UpdateFrontpageListViews_1.default;
const Config_1 = require("./Config");
exports.DOCUMENT_LIBRARY = Config_1.DOCUMENT_LIBRARY;
exports.FRONTPAGE_LISTS = Config_1.FRONTPAGE_LISTS;
exports.FRONTPAGE_LISTS_VIEQUERY = Config_1.FRONTPAGE_LISTS_VIEQUERY;
exports.PROJECTPHASE_FIELD = Config_1.PROJECTPHASE_FIELD;
