export const SubHeaderLabelFormats = {
    yearShort: "YY",
    yearLong: "YYYY",
    monthShort: "MM YYYY",
    monthMedium: "MMM YYYY",
    monthLong: "MMMM YYYY",
    dayShort: "D",
    dayMedium: "dd D",
    dayMediumLong: "ddd, Do",
    dayLong: "dddd, Do",
    hourShort: "HH",
    hourLong: "HH:00",
    minuteShort: "mm",
    minuteLong: "HH:mm",
};
