"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const InitialView_1 = require("./InitialView");
exports.InitialView = InitialView_1.default;
const SummaryView_1 = require("./SummaryView");
exports.SummaryView = SummaryView_1.default;
const ChangingPhaseView_1 = require("./ChangingPhaseView");
exports.ChangingPhaseView = ChangingPhaseView_1.default;
const GateApprovalView_1 = require("./GateApprovalView");
exports.GateApprovalView = GateApprovalView_1.default;
const ErrorInformationView_1 = require("./ErrorInformationView");
exports.ErrorInformationView = ErrorInformationView_1.default;
var View;
(function (View) {
    View[View["Initial"] = 0] = "Initial";
    View[View["Summary"] = 1] = "Summary";
    View[View["Confirm"] = 2] = "Confirm";
    View[View["ChangingPhase"] = 3] = "ChangingPhase";
    View[View["GateApproval"] = 4] = "GateApproval";
    View[View["ErrorInformation"] = 5] = "ErrorInformation";
})(View = exports.View || (exports.View = {}));
