export const PROJECTSTATS_LOADING_TEXT = "Henter data...";
export const PROJECTSTATS_ERROR_TEXT = "Det skjedde en feil under lasting av data.";
export const PROJECTSTATS_NO_CHARTS_TEXT = "Det er ikke konfigurert opp noen grafer.";
export const PROJECTSTATS_NO_DATA_TEXT = "Ingen prosjekter funnet.";
export const DEFAULT_TOGGLE_ON_TEXT = "Ja";
export const DEFAULT_TOGGLE_OFF_TEXT = "Nei";
export const SHOW_LEGEND_LABEL = "Vis merkelapp";
export const SELECT_PROJECT_NAME = "Velg prosjekt:";
export const SELECT_WIDTH_NAME = "Bredde";
